version: "3.8"
services:
  telegram_notify:
    build:
      context: .
    image: telegram_notify:development
    env_file: .env
    environment: 
      - PYTHONPATH=/app
    ports:
      - 5425:8990
    volumes:
      - ./config:/config
    restart: unless-stopped