version: "3.8"
services:
  telegram_notify:
    build:
      context: .
    image: telegram_notify:latest
    env_file: .env
    environment: 
      - PYTHONPATH=/app
    ports:
      - 8990:8990
    volumes:
      - ./:/config
      - ./:/app # For development
    restart: unless-stopped